channels:
  - anaconda
  - defaults
dependencies:
  - python==3.8.3
  - pip==20.1.1
  - pip:
    - google-auth==1.20.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - aiohttp==3.6.0
    - uvicorn==0.11.5
    - fastapi==0.58.0
    - asyncio-nats-client==0.10.0
    - aiologger==0.5.0
    - jsonschema==3.2.0
    - redis==3.5.3
    - pytest==5.4.3
    - kubernetes==11.0.0
