channels:
  - anaconda
  - defaults
dependencies:
  - python==3.8.3
  - pip==20.1.1
  - pip:
    - aiohttp==3.6.2
    - uvicorn==0.11.5
    - fastapi==0.58.1
    - asyncio-nats-client==0.10.0
    - aiologger==0.5.0
    - jsonschema==3.2.0
    - redis==3.5.3
    - pytest==5.4.3